baseURL = "https://Fundacion-de-valores.github.io/Ingles-Material/"
languageCode = "es"
title = "English for Call Center"
theme = "congo"

[params]
  colorScheme = "blowfish" # Un tema oscuro/claro elegante
  description = "Material del curso de inglés"
  showTableOfContents = true

[params.footer]
  showAppearanceSwitcher = false

[[menus.main]]
  name = ""
  weight = 10
  [menus.main.params]
    action = "appearance"

[params.article]
  showPagination = false

  [markup.goldmark.renderer]
  unsafe = true